<?php

function skin_menu() {

    $items = array();

    $items['skin'] = array(
        'title' => 'Skin Builder',
        'access arguments' => array('administer skin'),
        'page callback' => 'skin_builder_page',
        'file' => 'skin.pages.inc',
        'type' => MENU_CALLBACK,
    );
    $items['skin/save'] = array(
        'title' => 'Skin Builder',
        'access arguments' => array('administer skin'),
        'page callback' => 'skin_save_page',
        'file' => 'skin.pages.inc',
        'type' => MENU_CALLBACK,
    );
    $items['skin/process'] = array(
        'title' => 'Skin Process',
        'access arguments' => array('administer skin'),
        'page callback' => 'skin_process_page',
        'file' => 'skin.process.pages.inc',
        'type' => MENU_CALLBACK,
    );

    return $items;
}

function skin_permission() {
    return array(
        'administer skin' => array(
            'title' => t('Administer skin'),
            'description' => t('Perform administration custom skin.'),
        ),
    );
}

function skin_theme($existing, $type, $theme, $path) {
    return array(
        'skin_builder_page' => array(
            'variables' => array(),
            'template' => 'skin_builder_page',
        ),
    );
}

